plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
  - liquid_reading_time
  - liquid_pluralize
  - kramdown
  - kramdown-parser-gfm
  # - rouge
  - redcarpet
sass:
    style: compressed

