plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
  - liquid_reading_time
  - liquid_pluralize
  - kramdown
  - kramdown-parser-gfm
sass:
    style: compressed

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https\://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
#     syntax_highlighter: rouge
#     syntax_highlighter_opts:
#       css_class: highlight
#       span:
#         line_numbers: false
#       block:
#         line_numbers: true
#         start_line: 1